### ISSUE TITLE
Node 14 Support

### ISSUE THREAD

**Issue by james-soak** [garretua/strapi-provider-upload-aws-s3-enhanced#1]
Hello,

Thanks for making this plugin - we have been looking to use it as it nicely provides CDN URL support. Unfortunately we have had difficulties in deploying it to Heroku due to the engine constraint in `package.json`:

```
"node": ">=10.16.0 <14.0.0",
```

Is there anything code-wise preventing its use on Node 14, if not would it be possible to push a patch out to allow it?

Many thanks,
James

**Comment by alexmukho** [comment]
Hey @james-soak,

I believe that's because Node 14 was in beta a while ago. Seems like everything works fine so far. I've published a new version 3.5.2.
