### ISSUE TITLE
Support for Private ACL?

### ISSUE THREAD

**Issue by Dave-Biddle-Soak** [garretua/strapi-provider-upload-aws-s3-enhanced#2]
Hi,

First of all thanks for this provider! 

I was wondering if there's any intention to allow passing a custom ACL parameter for the S3 client at all? I'm getting:

```bash
error AccessDenied: Access Denied
strapi |     at Request.extractError (/srv/app/node_modules/aws-sdk/lib/services/s3.js:700:35)
```
It looks like this is due to a hard-coded config parameter:

https://github.com/garretua/strapi-provider-upload-aws-s3-enhanced/blob/bc2458ce284e9f6cdcffd157f58294143c379906/lib/index.js#L87

The bucket I'm trying to use is set to 'private', so upload is failing. 

Thanks!

**Comment by alexmukho** [comment]
Hi,

I can't actively maintain this plugin. I'll try to make some time next week. But feel free to send your PR if you want to.

**Comment by pimsomeday** [comment]
@garretua i've created [a PR ](https://github.com/garretua/strapi-provider-upload-aws-s3-enhanced/pull/6)

**Comment by alexmukho** [comment]
@pimsomeday great, thanks.
